sudo: required

language: generic

before_script:
  - curl --fail --location https://github.com/mvdan/sh/releases/download/v2.6.3/shfmt_v2.6.3_linux_amd64 > /usr/local/bin/shfmt
  - chmod +x /usr/local/bin/shfmt

script:
  - shfmt --version
  - shellcheck --version
  - make test
